hwi_oauth:
# an optional setting to configure a query string parameter which can be used to redirect
# the user after authentication, e.g. /connect/facebook?_destination=/my/destination will
# redirect the user to /my/destination after facebook authenticates them.  If this is not
# set then the user will be redirected to the original resource that they requested, or
# the base address if no resource was requested.  This is similar to the behaviour of
# [target_path_parameter for form login](https://symfony.com/doc/5.4/security/form_login.html).
# target_path_parameter: _destination

# an optional setting to use the HTTP REFERER header to be used in case no
# previous URL was stored in the session (i.e. no resource was requested).
# This is similar to the behaviour of
# [using the referring URL for form login](https://symfony.com/doc/5.4/security/form_login.html#using-the-referring-url).
# use_referer: true

# here you will add one (or more) configurations for resource owners
# and other settings you want to adjust in this bundle, just checkout the list below!
  firewall_names: [main]
  resource_owners:
    google:
      type:                google
      client_id:           '%env(HWI_GOOGLE_CLIENT_ID)%'
      client_secret:       '%env(HWI_GOOGLE_CLIENT_SECRET)%'
      scope:               "email profile"