twig:
    file_name_pattern: '*.twig'

    form_themes:
        - '@Tabler/layout/form-theme.html.twig'
    globals:
        tntClassifier: '@App\Service\TNTClassifier'

when@test:
    twig:
        strict_variables: true
