version: '2'

# http://geekyplatypus.com/dockerise-your-php-application-with-nginx-and-php7-fpm/
services:
    web:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - ./:/code
            - ./docker/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build:
          context: ./docker/
          dockerfile: Dockerfile-php.yml
        #image: php:7-fpm
        volumes:
            - ./:/code
#            - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
