version: '3'

# http://geekyplatypus.com/dockerise-your-php-application-with-nginx-and-php7-fpm/
services:
    web:
        image: nginx:latest
        ports:
            - "8000:80"
        env_file:
          - web-variables.env
        volumes:
            - code:/code
            - ./docker/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build:
          context: ./
          dockerfile: ./docker/Dockerfile-php.yml
        #image: php:7-fpm
        external_links:
          - mariadb_db_1
        volumes:
            - code:/code
#            - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - code-network

volumes:
  code:

networks:
    code-network:
        driver: bridge
