---
# http://geekyplatypus.com/dockerise-your-php-application-with-nginx-and-php7-fpm/
services:
    web:
        #build:
        #  context: ./
        #  dockerfile: ./docker/Dockerfile-nginx.yml
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - ./:/code
            - ./docker/site.conf:/etc/nginx/conf.d/default.conf

    php:
        build:
            context: ./docker/
            dockerfile: Dockerfile-php.yml
        #image: php:7-fpm
        volumes:
            - ./:/code
        #            - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        command: /usr/local/bin/docker-php-entrypoint-composer

    db:
        image: mariadb:10.5
        volumes:
            - ./db_initial:/docker-entrypoint-initdb.d/
        environment:
            MARIADB_DATABASE: budget
            MARIADB_USER: budget
            MARIADB_PASSWORD: budget
            MARIADB_ROOT_PASSWORD: ThisIsARootPassword

    adminer:
        image: adminer
        environment:
            - ADMINER_DESIGN=nette
            - ADMINER_DEFAULT_SERVER=mysql
        expose:
            - 8080
