version: '3'

# http://geekyplatypus.com/dockerise-your-php-application-with-nginx-and-php7-fpm/
services:
    web:
        #build:
        #  context: ./
        #  dockerfile: ./docker/Dockerfile-nginx.yml
        image: nginx:latest
        restart: always
        ports:
          - "8000:80"
        env_file:
          - web-variables.env
        volumes:
          - ./:/code
          #- ./app/config/parameters.yml:/code/app/config/parameters.yml
          - ./docker/site.conf:/etc/nginx/conf.d/default.conf
        networks:
          - nginxproxy_nginxproxy
          - code-network
    php:
        build:
          context: ./docker/
          dockerfile: Dockerfile-php.yml
        restart: always
        #image: php:7-fpm
        external_links:
          - mariadb_db_1
        volumes:
          - ./:/code
          - ./app/config/parameters.yml:/code/app/config/parameters.yml
#            - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        command: /usr/local/bin/docker-php-entrypoint-composer
        networks:
          - code-network
          - mariadb_mariadb


networks:
    mariadb_mariadb:
        external: true
    nginxproxy_nginxproxy:
        external: true
    code-network:
        driver: bridge
