services:
    sonata.admin.budgetaccount:
        class: EnvelopeBundle\Admin\BudgetAccountAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Accounts", label: "Budget Account" }
        arguments:
            - ~
            - App\Entity\BudgetAccount
            - ~
        calls:
            - [ setTranslationDomain, [EnvelopeBundle]]

    sonata.admin.account:
        class: EnvelopeBundle\Admin\AccountAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Accounts", label: "Bank Account" }
        arguments:
            - ~
            - App\Entity\Account
            - ~
        calls:
            - [ setTranslationDomain, [EnvelopeBundle]]

    sonata.admin.budgettransaction:
        class: EnvelopeBundle\Admin\BudgetTransactionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Transactions", label: "Budget Transactions" }
        arguments:
            - ~
            - App\Entity\BudgetTransaction
            - ~
        calls:
            - [ setTranslationDomain, [EnvelopeBundle]]

    sonata.admin.transaction:
        class: EnvelopeBundle\Admin\TransactionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Transactions", label: "Bank Transactions" }
        arguments:
            - ~
            - App\Entity\Transaction
            - ~
        calls:
            - [ setTranslationDomain, [EnvelopeBundle]]

    sonata.admin.autocodesearch:
        class: EnvelopeBundle\Admin\AutoCodeSearchAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Coding", label: "Auto Code Searches" }
        arguments:
            - ~
            - App\Entity\AutoCodeSearch
            - ~
        calls:
            - [ setTranslationDomain, [EnvelopeBundle]]

    sonata.admin.budgettemplate:
        class: EnvelopeBundle\Admin\TemplateAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Template", label: "Budget Templates" }
        arguments:
            - ~
            - App\Entity\Budget\Template
            - ~
        calls:
            - [ setTranslationDomain, [EnvelopeBundle]]

    sonata.admin.budgettemplatetransaction:
        class: EnvelopeBundle\Admin\TemplateTransactionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Template", label: "Budget Template Transactions" }
        arguments:
            - ~
            - App\Entity\Budget\TemplateTransaction
            - ~
        calls:
            - [ setTranslationDomain, [EnvelopeBundle]]

    sonata.admin.access_group:
        class: EnvelopeBundle\Admin\AccessGroupAdmin
        arguments: [~, App\Entity\AccessGroup, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: AccessGroup}

    sonata.admin.user:
        class: EnvelopeBundle\Admin\UserAdmin
        arguments: [~, App\Entity\User, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: User}

    envelope.admin.budget_group:
        class: EnvelopeBundle\Admin\BudgetGroupAdmin
        arguments: [~, App\Entity\BudgetGroup, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "Accounts", label: "Budget Group" }

    envelope.admin.external_connector:
        class: EnvelopeBundle\Admin\ExternalConnectorAdmin
        arguments: [~, App\Entity\ExternalConnector, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: ExternalConnector }
        public: true
