services:
    sonata.admin.budgetaccount:
        class: EnvelopeBundle\Admin\BudgetAccountAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Accounts", label: "Budget Account" }
        arguments:
            - ~
            - EnvelopeBundle\Entity\BudgetAccount
            - ~
        calls:
            - [ setTranslationDomain, [EnvelopeBundle]]

    sonata.admin.account:
        class: EnvelopeBundle\Admin\AccountAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Accounts", label: "Bank Account" }
        arguments:
            - ~
            - EnvelopeBundle\Entity\Account
            - ~
        calls:
            - [ setTranslationDomain, [EnvelopeBundle]]

    sonata.admin.budgettransaction:
        class: EnvelopeBundle\Admin\BudgetTransactionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Transactions", label: "Budget Transactions" }
        arguments:
            - ~
            - EnvelopeBundle\Entity\BudgetTransaction
            - ~
        calls:
            - [ setTranslationDomain, [EnvelopeBundle]]

    sonata.admin.transaction:
        class: EnvelopeBundle\Admin\TransactionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Transactions", label: "Bank Transactions" }
        arguments:
            - ~
            - EnvelopeBundle\Entity\Transaction
            - ~
        calls:
            - [ setTranslationDomain, [EnvelopeBundle]]

    sonata.admin.autocodesearch:
        class: EnvelopeBundle\Admin\AutoCodeSearchAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Coding", label: "Auto Code Searches" }
        arguments:
            - ~
            - EnvelopeBundle\Entity\AutoCodeSearch
            - ~
        calls:
            - [ setTranslationDomain, [EnvelopeBundle]]

    sonata.admin.budgettemplate:
        class: EnvelopeBundle\Admin\TemplateAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Template", label: "Budget Templates" }
        arguments:
            - ~
            - EnvelopeBundle\Entity\Budget\Template
            - ~
        calls:
            - [ setTranslationDomain, [EnvelopeBundle]]

    sonata.admin.budgettemplatetransaction:
        class: EnvelopeBundle\Admin\TemplateTransactionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Template", label: "Budget Template Transactions" }
        arguments:
            - ~
            - EnvelopeBundle\Entity\Budget\TemplateTransaction
            - ~
        calls:
            - [ setTranslationDomain, [EnvelopeBundle]]

    sonata.admin.access_group:
        class: EnvelopeBundle\Admin\AccessGroupAdmin
        arguments: [~, EnvelopeBundle\Entity\AccessGroup, EnvelopeBundle:AccessGroupAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: AccessGroup}
