avanzu_admin_profile:
    path: /profile/{userid}/
    defaults: { _controller: EnvelopeBundle:Default:profile }

avanzu_admin_logout:
    path: /logout

# redirecting the admin home
root:
    path: /
    defaults: { _controller: EnvelopeBundle:Default:dashboard }
    #defaults:
    #    _controller: FrameworkBundle:Redirect:redirect
    #    route: envelope_transactions
    #    permanent: true

envelope_autocode:
    path:   /autocode/
    defaults: { _controller: EnvelopeBundle:Default:autoCode }

envelope_import:
    path:   /import/
    defaults: { _controller: EnvelopeBundle:Default:import }

envelope_transactions:
    path:   /transaction/list
    defaults: { _controller: EnvelopeBundle:Default:transactionsList}

envelope_transaction_new:
    path:   /transaction/new
    defaults: { _controller: EnvelopeBundle:Default:transactionList, id: 'new'}

envelope_transaction:
    path:   /transaction/{id}
    defaults: { _controller: EnvelopeBundle:Default:transactionList}

envelope_transactionAddBudgetTransaction:
    path:   /transaction/{id}/addbudgettransaction/
    defaults: { _controller: EnvelopeBundle:Default:transactionAddBudgetTransaction}


envelope_budgets:
    path:   /budgetaccounts/
    defaults: { _controller: EnvelopeBundle:Default:budgetAccountList}

envelope_budgettransactions:
    path:   /budgettransactions/{accountid}
    defaults: { _controller: EnvelopeBundle:Default:budgetTransactionList, accountid: null}

envelope_budget_templates:
    path:   /budgets/templates/
    defaults: { _controller: EnvelopeBundle:Default:budgetTemplateList}

envelope_budget_template_clone:
    path:   /budgets/templates/clone/{templateid}
    defaults: { _controller: EnvelopeBundle:Default:budgetTemplateClone}

envelope_budget_apply_template:
    path:   /budgets/templates/apply
    defaults: { _controller: EnvelopeBundle:Default:applyBudgetTemplate}