envelope_homepage:
    path:     /hello/{name}
    defaults: { _controller: EnvelopeBundle:Default:index }

envelope_transactions:
    path:   /transactions/
    defaults: { _controller: EnvelopeBundle:Default:transactionList}

envelope_budgets:
    path:   /budgetaccounts/
    defaults: { _controller: EnvelopeBundle:Default:budgetAccountList}

envelope_budgettransactions:
    path:   /budgettransactions/{accountid}
    defaults: { _controller: EnvelopeBundle:Default:budgetTransactionList, accountid: null}
