envelope_autocode:
    path:   /autocode/
    defaults: { _controller: EnvelopeBundle:Default:autoCode }

envelope_autocode_edit_search:
    path:   /autocode/edit/{id}
    defaults: { _controller: EnvelopeBundle:Default:autoCodeSearchEdit }

envelope_autocode_delete_search:
    path:   /autocode/delete/{id}
    defaults: { _controller: EnvelopeBundle:Default:autoCodeSearchDelete }
    methods:  [POST]


envelope_import:
    path:   /import/
    defaults: { _controller: EnvelopeBundle:Default:import }



envelope_transactions:
    path:   /transaction/list
    defaults: { _controller: EnvelopeBundle:Default:transactionsList}

envelope_transaction_new:
    path:   /transaction/new
    defaults: { _controller: EnvelopeBundle:Default:transactionList, id: 'new'}

envelope_transaction:
    path:   /transaction/{id}
    defaults: { _controller: EnvelopeBundle:Default:transactionList}

envelope_transactionAddBudgetTransaction:
    path:   /transaction/{id}/addbudgettransaction/
    defaults: { _controller: EnvelopeBundle:Default:transactionAddBudgetTransaction}


envelope_budgets:
    path:   /budgetaccounts/
    defaults: { _controller: EnvelopeBundle:Default:budgetAccountList}

envelope_budget_templates:
    path:   /budgets/templates/
    defaults: { _controller: EnvelopeBundle:Default:budgetTemplateList}

envelope_budget_template_clone:
    path:   /budgets/templates/clone/{templateid}
    defaults: { _controller: EnvelopeBundle:Default:budgetTemplateClone}

envelope_budget_apply_template:
    path:   /budgets/templates/apply
    defaults: { _controller: EnvelopeBundle:Default:applyBudgetTemplate}

envelope_budget_template_edit:
    path:   /budgets/template/edit/{id}
    defaults: { _controller: EnvelopeBundle:Default:budgetTemplateEdit}

envelope_budget_template_delete:
    path:     /budgets/template/delete/{id}
    defaults: { _controller: EnvelopeBundle:Default:budgetTemplateDelete }
    methods:  [POST]

envelope_budget_stats:
    path:   /stats/
    defaults: { _controller: EnvelopeBundle:Stats:budgetStats}

envelope_budget_stats_spending:
    path:   /stats/spending
    defaults: { _controller: EnvelopeBundle:Stats:spendingStats}

envelope_budget_search:
    path:   /search/
    defaults: { _controller: EnvelopeBundle:Search:search}
