avanzu_admin_profile:
    path: /profile/{userid}/
    defaults: { _controller: EnvelopeBundle:Default:profile }

avanzu_admin_logout:
    path: /logout

# redirecting the admin home
#root:
#    path: /
#    defaults: { _controller: EnvelopeBundle:Default:dashboard }
#    #defaults:
#    #    _controller: FrameworkBundle:Redirect:redirect
#    #    route: envelope_transactions
#    #    permanent: true

envelope_transactionAddBudgetTransaction:
    path:   /transaction/{id}/addbudgettransaction/
    defaults: { _controller: EnvelopeBundle:Default:transactionAddBudgetTransaction}


envelope_budget_template_clone:
    path:   /budgets/templates/clone/{templateid}
    defaults: { _controller: EnvelopeBundle:Default:budgetTemplateClone}

envelope_budget_template_edit:
    path:   /budgets/template/edit/{id}
    defaults: { _controller: EnvelopeBundle:Default:budgetTemplateEdit}

envelope_budget_template_delete:
    path:     /budgets/template/delete/{id}
    defaults: { _controller: EnvelopeBundle:Default:budgetTemplateDelete }
    methods:  [POST]

envelope_budget_search:
    path:   /search/
    defaults: { _controller: EnvelopeBundle:Search:search}

envelope_bulk_code:
    path: /bulkcode
    defaults: { _controller: EnvelopeBundle:Default:transactionBulkCode}
    methods:  [POST]