parameters:
    my_admin_bundle.menu_listener.class: EnvelopeBundle\EventListener\MyMenuItemListListener
    my_admin_bundle.show_user_listener.class: EnvelopeBundle\EventListener\MyShowUserListener

services:
    _defaults:
        autowire: true
        autoconfigure: true

    my_admin_bundle.menu_listener:
        class: "%my_admin_bundle.menu_listener.class%"
        tags:
            - { name: kernel.event_listener, event: theme.sidebar_setup_menu, method: onSetupMenu }
        arguments: ['@security.authorization_checker']

    my_admin_bundle.show_user_listener:
        class: "%my_admin_bundle.show_user_listener.class%"
        tags:
           - { name: kernel.event_listener, event: theme.navbar_user, method: onShowUser }
        arguments: ['@session', '@doctrine', '@service_container']
