FROM php:7.2-fpm

RUN apt-get update && apt-get install -y libpq-dev zlib1g-dev libicu-dev g++ git zip
RUN docker-php-ext-install pdo pdo_mysql pdo_pgsql bcmath intl
COPY --from=composer:1 /usr/bin/composer /usr/bin/composer

RUN echo 'date.timezone = "Australia/Brisbane"' > /usr/local/etc/php/conf.d/timezone.ini
RUN echo 'max_execution_time = 60' > /usr/local/etc/php/conf.d/executiontime.ini

# Bower
RUN apt-get install -y gnupg
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -

RUN apt-get install -y nodejs
RUN npm install -g bower
RUN ln -s /usr/bin/bower /usr/local/bin/bower
COPY ./docker-php-entrypoint-composer /usr/local/bin
