FROM php:8.3-fpm

RUN apt-get update && apt-get install -y libpq-dev zlib1g-dev libicu-dev g++ git zip
RUN docker-php-ext-install pdo pdo_mysql pdo_pgsql bcmath intl
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN echo 'date.timezone = "Australia/Brisbane"' > /usr/local/etc/php/conf.d/timezone.ini
RUN echo 'max_execution_time = 60' > /usr/local/etc/php/conf.d/executiontime.ini

COPY ./docker-php-entrypoint-composer /usr/local/bin
