# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

google_login:
    path: /login/check-google

logout:
    path: /logout

# TODO move all of these to annotations
#envelope:
#    resource: "@EnvelopeBundle/Resources/config/routing.yml"
#    prefix:   /composer require kevinpapst/adminlte-bundle

# app/config/routing.yml
#admin:
#    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
#    prefix: /admin
#
#_sonata_admin:
#    resource: .
#    type: sonata_admin
#    prefix: /admin